export const BatchTranscriptionEnv = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAX_SIZE_AUDIO: process.env.REACT_APP_MAX_SIZE_AUDIO_BATCH,
    MAX_TIME_PROCESSING: process.env.REACT_APP_MAX_TIME_PROCESSING_BATCH, 
    TIME_BETWEEN_EACH_POLLING: process.env.REACT_APP_TIME_BETWEEN_EACH_POLLING_BATCH,
};

export const DiarizationEnv = {
    API_KEY: process.env.REACT_APP_API_KEY,
    MAX_SIZE_AUDIO: process.env.REACT_APP_MAX_SIZE_AUDIO_DIARIZATION,
    MAX_TIME_PROCESSING: process.env.REACT_APP_MAX_TIME_PROCESSING_DIARIZATION, 
    TIME_BETWEEN_EACH_POLLING: process.env.REACT_APP_TIME_BETWEEN_EACH_POLLING_DIARIZATION,
    MAX_SPEAKERS: process.env.REACT_APP_MAX_SPEAKERS_DIARIZATION,
};